Add aggregate target for branch protection

diff --git a/.github/workflows/ci-unit-tests.yml b/.github/workflows/ci-unit-tests.yml
--- a/.github/workflows/ci-unit-tests.yml
+++ b/.github/workflows/ci-unit-tests.yml
@@ -12,8 +12,8 @@ permissions:
 jobs:
   make-test:
     strategy:
-        matrix:
-            os: [ubuntu-latest, macos-latest]
+      matrix:
+        os: [ubuntu-latest, macos-latest]
     runs-on: ${{ matrix.os }}
     timeout-minutes: 5
     steps:
@@ -30,3 +30,16 @@ jobs:
 
       - name: Run tests
         run: make test TEST_FLAGS=--test-force-exit PRETTIER="$PWD/node_modules/.bin/prettier" ESLINT="$PWD/node_modules/.bin/eslint"
+
+  make-test-matrix:
+    runs-on: ubuntu-latest
+    needs: make-test
+    if: always()
+    steps:
+      - name: Check matric status
+        run: |
+          if [ "${{ needs.make-test.result }}" != "success" ]; then
+            echo "Some matrix test branches failed or were cancelled"
+            exit 1
+          fi
+          echo "All matrix text branches completed successfully"
